### ISSUE TITLE
Error: Remote HEAD refers to nonexistent ref, unable to checkout

### ISSUE THREAD

**Issue by rmglennon** [mapzen/search-sandbox#3]
Error on git clone 
```
$ git clone https://github.com/mapzen/search-sandbox.git
Cloning into 'search-sandbox'...
remote: Counting objects: 103, done.
remote: Total 103 (delta 0), reused 0 (delta 0), pack-reused 103
Receiving objects: 100% (103/103), 50.63 KiB | 0 bytes/s, done.
Resolving deltas: 100% (51/51), done.
Checking connectivity... done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.
```
Fix: https://help.github.com/articles/error-remote-head-refers-to-nonexistent-ref-unable-to-checkout/

Looks like default branch (master?) has been deleted, so an admin needs to update the default branch in the GitHub settings. With this being on mapzen.com, we might not need GitHub pages now either.

**Comment by missinglink** [comment]
heya, I had a look in the github settings and it looks like the default branch is already set to `gh-pages`:

![ss](https://user-images.githubusercontent.com/738069/28066632-09550bae-663e-11e7-9b81-91ea99bf4bd3.png)

**Comment by missinglink** [comment]
I can confirm I get the same error on clone:

```bash
$ git clone https://github.com/mapzen/search-sandbox.git
Cloning into 'search-sandbox'...
remote: Counting objects: 103, done.
remote: Total 103 (delta 0), reused 0 (delta 0), pack-reused 103
Receiving objects: 100% (103/103), 50.63 KiB | 0 bytes/s, done.
Resolving deltas: 100% (51/51), done.
Checking connectivity... done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.
```

sorry, I'm not sure how to fix it :(

**Comment by missinglink** [comment]
right... so there is a workaround, but it's unfortunately not a fix:

```bash
$ rm -rf search-sandbox/
$ mkdir search-sandbox
$ cd search-sandbox/
$ git init
$ git remote add origin git@github.com:mapzen/search-sandbox.git
$ git fetch
$ git checkout gh-pages
```

**Comment by rmglennon** [comment]
thanks for the investigation, @missinglink!  I'm not why this error is happening either then if gh-pages is already the default. 

Last hope, what if we renamed gh-pages to master and built GitHub Pages off the master (which is an option now)?

I was able to workaround it locally and make a new branch for some work, although I haven't tried pushing up or anything yet.

**Comment by orangejulius** [comment]
I think I fixed this by changing the default branch in settings to `production`, and then back to `gh-pages`. Everyone try cloning now, it should be fine.

BTW looking at [this](https://stackoverflow.com/questions/11893678/warning-remote-head-refers-to-nonexistent-ref-unable-to-checkout) it appears the data was still all downloaded successfully.

**Comment by rmglennon** [comment]
Thanks, @orangejulius and @missinglink. 

Clones fine now, and git branch reports gh-pages and Production.
