### ISSUE TITLE
Example URL string should be plain text and not switch to HTML special characters

### ISSUE THREAD

**Issue by rmglennon** [mapzen/search-sandbox#4]
In this query: 

https://mapzen.com/search/explorer/?query=search/structured&address=201%20spear%20street&locality=san%20francisco&region=ca

the `&reg` in `region` gets converted to the HTML special character (`&reg;`) for registered trademark.

![image](https://user-images.githubusercontent.com/4380498/28191070-1e4188ca-67e3-11e7-84cd-d2e1b36ef676.png)

This is `<div id='query-preview' class="thin-border" style="padding: 15px; margin-bottom: 10px; word-wrap: break-word;"></div>` in index.html.

**Comment by dianashk** [comment]
Oh wow great catch!!!

**Comment by dianashk** [comment]
Fixed by #7
